rem KiCAD symlinks aanmaken, 2016.10.15
set DROPBOXPAD="B:\Dropbox en Onedrive\Dropbox (Persoonlijk)"
mklink /D "C:\Users\michiele\Documents\Dropbox(Michiel)"  %DROPBOXPAD%
mklink /D "C:\Users\michiele\Documents\Dropbox(EasyLab4kids)"  "B:\Dropbox en Onedrive\Dropbox(EasyLab4Kids)"

mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\walter" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\walter"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\JorgeAparicio" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\JorgeAparicio"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\Arduino" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\Arduino"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\Header_Sockets" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\Header_Sockets"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\3Dshapes_Michiel" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\3Dshapes_Michiel"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2tech" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ander" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ander"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\EnergyMicro.3dshapes" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\EnergyMicro.3dshapes"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ESP8266.3dshapes" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ESP8266.3dshapes"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\nicholasclewis" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\nicholasclewis"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\rmc" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\rmc"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\SMD_chips_alternative.3dshapes" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\SMD_chips_alternative.3dshapes"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\YT_Components" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\YT_Components"

mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_7seg" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_7seg"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_connector" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_connector"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_dip" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_dip"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_header" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_header"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_heatsink" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_heatsink"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_holesnpoles" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_holesnpoles"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_idc" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_idc"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_input_devices" 	"B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_input_devices"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_jumper"			"B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_jumper"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_lqfp" 				"B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_lqfp"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_meshconv_gui" 		"B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_meshconv_gui"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_msop" 				"B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_msop"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_passive" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_passive"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_power" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_power"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_so" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_so"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_son" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_son"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_sot" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_sot"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_terminal_block" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_terminal_block"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_tssop" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_tssop"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_usb" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_usb"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_vssop" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_vssop"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\packages3d\ab2_xtal" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\3dshapes\packges3d\ab2tech\ab2_xtal"

mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\ab2tech" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\ab2tech"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\Arduino_shields_Michiel.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\Arduino_shields_Michiel.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\ESP8266.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\ESP8266.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\freetronics_footprints.pretty"  "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\freetronics_footprints.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\sharebrained" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\sharebrained"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\SHIELD_ARDUINO.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\SHIELD_ARDUINO.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\swartskaap@gmail.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\swartskaap@gmail.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_battery_holders.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_battery_holders.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_logo.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_logo.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_conn_misc.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_conn_misc.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_conn_mkds.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_conn_mkds.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_conn_pc.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_conn_pc.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_conn_screw.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_conn_screw.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_details.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_details.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_indicators.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_indicators.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_pga.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_pga.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_pin_strip.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_pin_strip.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_pth_circuits.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_pth_circuits.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_pth_resistors.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_pth_resistors.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_relay.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_relay.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_rf_modules.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_rf_modules.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_smd_bga.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_smd_bga.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_smd_dil.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_smd_dil.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_smd_leds.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_smd_leds.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_smd_qfn.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_smd_qfn.pretty"
mklink /D "C:\Program Files\KiCad\share\kicad\modules\footprints_ander\w_switch.pretty" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)\michiele\Aruino\PCB Ontwerp\KiCAD\KiCAD_libraries\share\kicad\footprints\w_switch.pretty"

mklink /D "C:\Program Files\KiCad\share\kicad\library\library.oshec.org" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\library.oshec.org"
mklink /D "C:\Program Files\KiCad\share\kicad\library\ab2tech" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\ab2tech"
mklink /D "C:\Program Files\KiCad\share\kicad\library\ander" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\ander"
mklink /D "C:\Program Files\KiCad\share\kicad\library\arduino" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\arduino"
mklink /D "C:\Program Files\KiCad\share\kicad\library\kicadlib.org" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\kicadlib.org"
mklink /D "C:\Program Files\KiCad\share\kicad\library\lib_michiel" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\lib_michiel"
mklink /D "C:\Program Files\KiCad\share\kicad\library\Symbols" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\Symbols"
mklink /D "C:\Program Files\KiCad\share\kicad\library\walter" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\walter"
mklink /D "C:\Program Files\KiCad\share\kicad\library\YT_Components" "B:\Dropbox en Onedrive\Dropbox\michiele\michiele\Aruino\PCB Ontwerp\KiCAD\share\kicad\modules\YT_Components"

mklink "C:\Users\michiele\AppData\Roaming\kicad\kicad" "B:\Dropbox en Onedrive\Dropbox\michiele\Aruino\PCB Ontwerp\KiCAD\AppData\Roaming\kicad\windows\kicad"
mklink "C:\Users\michiele\AppData\Roaming\kicad\fp-lib-table" "B:\Dropbox en Onedrive\Dropbox\michiele\Aruino\PCB Ontwerp\KiCAD\AppData\Roaming\kicad\windows\fp-lib-table"
mklink "C:\Users\michiele\AppData\Roaming\kicad\pcbnew" "B:\Dropbox en Onedrive\Dropbox\michiele\Aruino\PCB Ontwerp\KiCAD\AppData\Roaming\kicad\windows\pcbnew"
mklink "C:\Users\michiele\AppData\Roaming\kicad\kicad_common" "B:\Dropbox en Onedrive\Dropbox\michiele\Aruino\PCB Ontwerp\KiCAD\AppData\Roaming\kicad\windows\kicad_common"
rem mklink "C:\Users\michiele\AppData\Roaming\kicad\pl_editor" "B:\Dropbox en Onedrive\Dropbox\michiele\Aruino\PCB Ontwerp\KiCAD\AppData\Roaming\kicad\windows\pl_editor"
mklink "C:\Users\michiele\AppData\Roaming\kicad\kicad.pro" "B:\Dropbox en Onedrive\Dropbox\michiele\Aruino\PCB Ontwerp\KiCAD\AppData\Roaming\kicad\windows\kicad.pro"

mklink /D "C:\Users\michiele\Google drive" "B:\Google drive"
mklink /D "C:\Users\michiele\Documents\Opgeslagen spellen" "C:\Users\michiele\Saved Games" 


rem mklink /D  "C:\Users\michiele\Saved Games\DCS" "B:\Opgeslagen spellen\DCS"
rem mklink /D  "C:\Users\michiele\Saved Games\DCS.openbeta" "C:\Users\michiele\Saved Games\DCS.openbeta"
rem mklink /D  "C:\Users\michiele\Saved Games\AriesWings" "C:\Users\michiele\Saved Games\AriesWings"
rem mklink /D  "C:\Users\michiele\Saved Games\Assassin's Creed Brotherhood" "C:\Users\michiele\Saved Games\Assassin's Creed Brotherhood"
rem mklink /D  "C:\Users\michiele\Saved Games\Command & Conquer 3 Tiberium Wars Enhanced" "C:\Users\michiele\Saved Games\Command & Conquer 3 Tiberium Wars Enhanced"
rem mklink /D  "C:\Users\michiele\Saved Games\Command and Conquer 3 Kanes Wrath" "C:\Users\michiele\Saved Games\Command and Conquer 3 Kanes Wrath"
rem mklink /D  "C:\Users\michiele\Saved Games\Crysis 3 MP Open Beta" "C:\Users\michiele\Saved Games\Crysis 3 MP Open Beta"
rem mklink /D  "C:\Users\michiele\Saved Games\Crysis2" "C:\Users\michiele\Saved Games\Crysis2"
rem mklink /D  "C:\Users\michiele\Saved Games\edModelViewer" "C:\Users\michiele\Saved Games\edModelViewer"
rem mklink /D  "C:\Users\michiele\Saved Games\Frontier Developments" "C:\Users\michiele\Saved Games\Frontier Developments"
rem mklink /D  "C:\Users\michiele\Saved Games\Red Alert 3" "C:\Users\michiele\Saved Games\Red Alert 3"
rem mklink /D "C:\Users\michiele\Documents\Dropbox(Michiel)" "B:\Dropbox en Onedrive\Dropbox (Persoonlijk)"
rem mklink /D "C:\Users\michiele\Documents\Dropbox(EasyLab4Kids)" "B:\Dropbox en Onedrive\Dropbox (EasyLab4Kids)"
rem mklink /D "C:\Users\michiele\Documents\Onedrive" "B:\Dropbox en Onedrive\OneDrive"

